# Generated by Django 3.0.8 on 2020-11-26 09:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('company_email', models.EmailField(max_length=60, unique=True)),
                ('address_line', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='ZIP/Postal code')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('pool_capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'ordering': ['-company_name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(default='someemail@gmail.com', max_length=200, null=True, unique=True)),
                ('apt', models.IntegerField(default='205')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_set', to='reservations.Company')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date(2020, 11, 27))),
                ('date_created', models.DateField(default=datetime.date(2020, 11, 26), editable=False)),
                ('notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('pool_capacity', models.IntegerField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_set', to='reservations.Company')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='LeaseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('relation', models.CharField(choices=[('husband', 'Husband'), ('wife', 'Wife'), ('daughter', 'Daughter'), ('son', 'Son'), ('relative', 'Relative')], max_length=100, null=True)),
                ('lease_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_member_set', to='reservations.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('9am-11am', '9am-11am'), ('12pm-2pm', '12pm-2pm'), ('3pm-5pm', '3pm-5pm')], default='Choose a time window', max_length=100, null=True)),
                ('capacity', models.IntegerField(blank=True, default=13, editable=False)),
                ('notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslot_set', to='reservations.Day')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_show', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='reservations.Company')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='reservations.Customer')),
                ('party_members', models.ManyToManyField(blank=True, to='reservations.LeaseMember')),
                ('timeslot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='reservations.TimeSlot')),
            ],
        ),
    ]
