# Generated by Django 3.0.8 on 2020-07-31 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoolDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('pool_status', models.BooleanField()),
                ('PoolDay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.PoolDay')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.TextField(blank=True)),
                ('party_size', models.IntegerField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('TimeSlot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.TimeSlot')),
            ],
        ),
    ]
