# Generated by Django 3.0.8 on 2020-07-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poolday',
            old_name='content',
            new_name='day_notes',
        ),
        migrations.RemoveField(
            model_name='poolday',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='poolday',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='poolday',
            name='title',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='poolday',
            name='condition',
            field=models.TextField(default='Not Full'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='condition',
            field=models.TextField(default='Not Full'),
        ),
    ]
