# Generated by Django 3.0.8 on 2020-09-24 05:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200919_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-day']},
        ),
        migrations.AddField(
            model_name='day',
            name='pool_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_line',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_set', to='reservations.Company'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='someemail@gmail.com', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lease_members',
            field=models.TextField(blank=True, verbose_name='Lease Members'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lease_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Customer'),
        ),
        migrations.AlterField(
            model_name='day',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_set', to='reservations.Company'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 9, 24), editable=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(default=datetime.date(2020, 9, 25)),
        ),
    ]
