# Generated by Django 3.0.8 on 2020-08-09 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200809_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='day_after_field',
            field=models.DateField(default=datetime.datetime(2020, 8, 10, 0, 58, 59, 99252)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_slot',
            field=models.CharField(choices=[('9am-11am', '9am-11am'), ('12pm-2pm', '12pm-2pm'), ('3pm-5pm', '3pm-5pm')], default='Choose a time window', max_length=10, null=True),
        ),
    ]
