# Generated by Django 3.0.8 on 2020-07-31 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200731_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poolday',
            old_name='condition',
            new_name='notes',
        ),
    ]
