# Generated by Django 3.0.8 on 2020-09-25 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200924_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='time_slot',
            field=models.CharField(choices=[('9am-11am', '9am-11am'), ('12pm-2pm', '12pm-2pm'), ('3pm-5pm', '3pm-5pm')], default='Choose a time window', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LeaseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('relation', models.CharField(choices=[('husband', 'Husband'), ('wife', 'Wife'), ('daughter', 'Daughter'), ('son', 'Son'), ('relative', 'Relative')], max_length=100, null=True)),
                ('lease_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_member_set', to='reservations.Customer')),
            ],
        ),
    ]
