# Generated by Django 3.0.8 on 2020-07-31 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200731_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poolday',
            old_name='notes',
            new_name='date',
        ),
    ]
