# Generated by Django 3.0.8 on 2020-08-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200809_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_after_field',
            field=models.DateField(blank=True, default=10, null=True),
        ),
    ]
