# Generated by Django 3.0.8 on 2020-09-26 02:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200924_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='lease_members',
        ),
        migrations.AlterField(
            model_name='day',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 9, 25), editable=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(default=datetime.date(2020, 9, 26)),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='party_members',
        ),
        migrations.AddField(
            model_name='reservation',
            name='party_members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.LeaseMember'),
        ),
    ]
