# Generated by Django 3.0.8 on 2020-08-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20200809_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day_after',
            new_name='nextday',
        ),
    ]
