# Generated by Django 3.0.8 on 2020-07-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20200731_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolday',
            name='date',
            field=models.CharField(default='July 30th 2020 (Just Text)', max_length=50),
        ),
    ]
