# Generated by Django 3.0.8 on 2020-08-06 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20200731_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('lease_members', models.ManyToManyField(related_name='_customer_lease_members_+', to='reservations.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='TimeSlot',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='party',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='PoolDay',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='pool_status',
            field=models.BooleanField(default='Full'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='PoolDay',
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.Customer'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.Day'),
        ),
    ]
