# Generated by Django 3.0.8 on 2020-09-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20200925_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='current_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
