# Generated by Django 3.0.8 on 2020-08-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20200809_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day_created',
            new_name='date_created',
        ),
    ]
