# Generated by Django 3.0.8 on 2020-08-06 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20200805_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='pool_status',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='capacity',
            field=models.IntegerField(blank=True, default=13),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='pool_status_full',
            field=models.BooleanField(default=False, verbose_name='Time slot at capacity'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lease_members',
            field=models.ManyToManyField(blank=True, related_name='_customer_lease_members_+', to='reservations.Customer'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 7)),
        ),
    ]
