# Generated by Django 3.0.8 on 2020-08-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20200806_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time_name',
            field=models.CharField(default='Choose a time window', max_length=10, null=True),
        ),
    ]
