# Generated by Django 3.0.8 on 2020-09-26 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_timeslot_current_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='lease_members',
            field=models.ManyToManyField(to='reservations.LeaseMember'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 9, 26), editable=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(default=datetime.date(2020, 9, 27)),
        ),
    ]
