# Generated by Django 3.0.8 on 2020-08-09 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20200809_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='reservations.Customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Day'),
        ),
    ]
