# Generated by Django 3.0.8 on 2020-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20200806_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.AddField(
            model_name='reservation',
            name='party_members',
            field=models.ManyToManyField(to='reservations.Customer'),
        ),
    ]
