# Generated by Django 3.0.8 on 2020-08-11 07:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20200809_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 8, 11)),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(default=datetime.date(2020, 8, 12)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservaation_set', to='reservations.Customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='reservations.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='capacity',
            field=models.IntegerField(blank=True, default=13, editable=False),
        ),
    ]
