# Generated by Django 3.0.8 on 2020-08-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20200806_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('timeslot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.TimeSlot')),
                ('nickname', models.CharField(blank=True, max_length=10)),
            ],
            bases=('reservations.timeslot',),
        ),
    ]
