# Generated by Django 3.0.8 on 2020-08-11 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_auto_20200811_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='pool_status_full',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='reservations.Customer'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslot_set', to='reservations.Day'),
        ),
    ]
