# Generated by Django 3.0.8 on 2020-09-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_auto_20200927_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='lease_members',
        ),
        migrations.AddField(
            model_name='reservation',
            name='party_members',
            field=models.ManyToManyField(blank=True, to='reservations.LeaseMember'),
        ),
    ]
