# Generated by Django 3.0.8 on 2020-08-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_submodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='party_members',
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.Customer'),
        ),
        migrations.DeleteModel(
            name='SubModel',
        ),
    ]
