# Generated by Django 3.0.8 on 2020-08-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20200806_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='party_members',
            field=models.ManyToManyField(related_name='party_members', to='reservations.Customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='reservations.Customer'),
        ),
    ]
