# Generated by Django 3.0.8 on 2020-09-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20200927_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='current_capacity',
        ),
    ]
