# Generated by Django 3.0.8 on 2020-08-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20200806_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='time_name',
            new_name='time_slot',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='party_size',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='party_members',
            field=models.ManyToManyField(blank=True, related_name='party_members', to='reservations.Customer'),
        ),
    ]
