# Generated by Django 3.0.8 on 2020-09-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_remove_timeslot_current_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['-day']},
        ),
    ]
