# Generated by Django 3.0.8 on 2020-08-07 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20200806_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='apt_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 8)),
        ),
    ]
