# Generated by Django 3.0.8 on 2020-08-30 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_timeslot_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 8, 30)),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(default=datetime.date(2020, 8, 31)),
        ),
    ]
