# Generated by Django 3.0.8 on 2020-09-05 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_auto_20200830_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='day',
        ),
        migrations.RemoveField(
            model_name='day',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.date(2020, 9, 4)),
        ),
        migrations.AlterField(
            model_name='day',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 9, 4)),
        ),
    ]
