# Generated by Django 3.0.8 on 2020-09-05 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_auto_20200904_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.date(2020, 9, 5)),
        ),
    ]
