# Generated by Django 3.0.8 on 2020-09-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_auto_20200904_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='day',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
