# Generated by Django 3.0.8 on 2020-09-07 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 9, 7)),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(default=datetime.date(2020, 9, 8)),
        ),
    ]
