# Generated by Django 3.0.8 on 2020-09-08 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_auto_20200907_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.Company'),
        ),
    ]
